name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:

  build_mingw_toolchain:
    name: Linux MinGW-W64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Compile Toolchain
      run: |
        chmod 755 *
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        CWD=$(pwd)
        ./mingw-w64-build --disable-gdb x86_64 ~/toolchains
        ./mingw-w64-build x86_64.clean ~/toolchains
        ./mingw-w64-build pkgclean ~/toolchains
        tar cvzf mingw-w64-build-$BUILD_VERSION-x86_64-linux.tar.gz -C ~/toolchains/ .
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  build_mingw_toolchain_i686:
    name: Linux MinGW-W64 i686
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Compile Toolchain
      run: |
        chmod 755 *
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        CWD=$(pwd)
        ./mingw-w64-build --disable-gdb i686 ~/toolchains
        ./mingw-w64-build i686.clean ~/toolchains
        ./mingw-w64-build pkgclean ~/toolchains
        tar cvzf mingw-w64-build-$BUILD_VERSION-i686-linux.tar.gz -C ~/toolchains/ . 
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
  build_mingw_toolchain_macOS:
    name: macOS MinGW-W64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile Toolchain
      run: |
        chmod 755 *
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        CWD=$(pwd)
        ./mingw-w64-build --disable-gdb x86_64 ~/toolchains
        ./mingw-w64-build x86_64.clean ~/toolchains
        ./mingw-w64-build pkgclean ~/toolchains
        tar cvzf mingw-w64-build-$BUILD_VERSION-x86_64-macos.tar.gz -C ~/toolchains/ .
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  build_mingw_toolchain_macOS_i686:
    name: macOS MinGW-W64 i686
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile Toolchain
      run: |
        chmod 755 *
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        CWD=$(pwd)
        ./mingw-w64-build --disable-gdb i686 ~/toolchains
        ./mingw-w64-build i686.clean ~/toolchains
        ./mingw-w64-build pkgclean ~/toolchains
        tar cvzf mingw-w64-build-$BUILD_VERSION-i686-macos.tar.gz -C ~/toolchains/ .
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
