name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:

  create_linux_packages_cache:
    name: Create Linux Packages Cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Download Packages
      run: |
        chmod +x mingw-w64-build
        ./mingw-w64-build download .
    - name: Cache Packages
      id: cache-packages-save
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-linux-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}

  create_macos_packages_cache:
    name: Create macOS Packages Cache
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v7
    - name: Download Packages
      run: |
        chmod +x mingw-w64-build
        ./mingw-w64-build download .
    - name: Cache Packages
      id: cache-packages-save
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-macos-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}

  build_mingw_toolchain_msvcrt_linux_x86_64:
    name: MinGW-w64 MSVCRT Linux x86_64
    runs-on: ubuntu-latest
    needs: create_linux_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-linux-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="msvcrt"
        BUILD_PLATFORM="linux"
        BUILD_ARCH="x86_64"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_msvcrt_linux_i686:
    name: MinGW-w64 MSVCRT Linux i686
    runs-on: ubuntu-latest
    needs: create_linux_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-linux-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="msvcrt"
        BUILD_PLATFORM="linux"
        BUILD_ARCH="i686"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_ucrt_linux_x86_64:
    name: MinGW-w64 UCRT Linux x86_64
    runs-on: ubuntu-latest
    needs: create_linux_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-linux-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="ucrt"
        BUILD_PLATFORM="linux"
        BUILD_ARCH="x86_64"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_ucrt_linux_i686:
    name: MinGW-w64 UCRT Linux i686
    runs-on: ubuntu-latest
    needs: create_linux_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-linux-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="ucrt"
        BUILD_PLATFORM="linux"
        BUILD_ARCH="i686"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_msvcrt_mac_x86-64:
    name: MinGW-w64 MSVCRT macOS x86_64
    runs-on: macos-14
    needs: create_macos_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-macos-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="msvcrt"
        BUILD_PLATFORM="macos"
        BUILD_ARCH="x86_64"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_msvcrt_mac_i686:
    name: MinGW-w64 MSVCRT macOS i686
    runs-on: macos-14
    needs: create_macos_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-macos-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="msvcrt"
        BUILD_PLATFORM="macos"
        BUILD_ARCH="i686"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_ucrt_mac_x86-64:
    name: MinGW-w64 UCRT macOS x86_64
    runs-on: macos-14
    needs: create_macos_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-macos-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="ucrt"
        BUILD_PLATFORM="macos"
        BUILD_ARCH="x86_64"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}

  build_mingw_toolchain_ucrt_mac_i686:
    name: MinGW-w64 UCRT macOS i686
    runs-on: macos-14
    needs: create_macos_packages_cache
    steps:
    - uses: actions/checkout@v7
    - name: Restore Packages Cache
      id: cache-packages-restore
      uses: actions/cache@v5.0.2
      with:
        path: .
        key: pkg-macos-${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.sha) }}-${{ github.run_id }}
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_MSVCRT="ucrt"
        BUILD_PLATFORM="macos"
        BUILD_ARCH="i686"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_MSVCRT}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        mkdir "${BUILD_TUPLE}"
        if [[ -d pkg ]]; then
          echo "Package cache hit."
          mv pkg "${BUILD_TUPLE}"/ || exit 1
        else
          echo "Package cache miss."
        fi
        chmod +x mingw-w64-build
        SUCCESS=false
        if ./mingw-w64-build --force --msvcrt="${BUILD_MSVCRT}" "${BUILD_ARCH}" "${BUILD_TUPLE}"; then
          SUCCESS=true
        fi
        tar -cvf ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar \
          $(find "${BUILD_TUPLE}"/build-* -type f -name "*.log") || true
        if [[ "${SUCCESS}" == true ]]; then
          ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
          ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
          ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
          tar -cvzf "${BUILD_TUPLE}".tar.gz "${BUILD_TUPLE}"
        else
          exit 1
        fi
    - name: Archive Build Logs Artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}
        path: |
          ${{ github.job }}-logs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.tar
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v4.0.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ github.token }}
